name: Node.js frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules and next build
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          node_modules
          .next/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn format
    - run: yarn lint
    - run: yarn build
#   - run: yarn test