name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://alexanderkonietzko.vercel.app/
            https://alexanderkonietzko.vercel.app/de
            https://alexanderkonietzko.vercel.app/blog
            https://alexanderkonietzko.vercel.app/guestbook
            https://alexanderkonietzko.vercel.app/about
            https://alexanderkonietzko.vercel.app/projects
          uploadArtifacts: false
          temporaryPublicStorage: true
          runs: 3
